[package]
name = "vec-set"
version = "0.1.0"
authors = ["Rüdiger Klaehn <rklaehn@gmail.com>"]
edition = "2018"

[dependencies]
alga = "0.9"
flip-buffer = { path = "../flip-buffer" }

[dev-dependencies]
quickcheck = "0.8"
